language: node_js
sudo: false
before_script:
  - npm install -g polymer-cli
  - polymer install
node_js: node
addons:
  firefox: '66.0'
  chrome: stable
script:
  - xvfb-run polymer test
cache:
  directories:
    - node_modules
